### ISSUE TITLE
Getting this error gnuplot.rb:219:in `instance_of?': class or module required (TypeError) when running examples.

### ISSUE THREAD

**Issue by DouglasAllen** [rdp/ruby_gnuplot#43]
I have Gnuplot installed on Windows 10 and is on the [path settings].
The gem version is 2.6.2 from a 'gem install gnuplot'

[Running] ruby "c:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\gnuplot-2.6.2\examples\sin_wave.rb"
c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:219:in `instance_of?': class or module required (TypeError)
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:219:in `plot_args'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `block in store_datasets'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `collect'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `store_datasets'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:102:in `initialize'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/examples/sin_wave.rb:4:in `new'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/examples/sin_wave.rb:4:in `block in <main>'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:74:in `block in open'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:73:in `popen'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:73:in `open'
	from c:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/examples/sin_wave.rb:3:in `<main>'

[Done] exited with code=1 in 0.708 seconds

That was in VS Code editor.
The command line would be similar but I'll give it to ya.
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:219:in `instance_of?': class or module required (TypeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:219:in `plot_args'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `block in store_datasets'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `collect'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:160:in `store_datasets'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:102:in `initialize'
        from sin_wave.rb:4:in `new'
        from sin_wave.rb:4:in `block in <main>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:74:in `block in open'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:73:in `popen'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gnuplot-2.6.2/lib/gnuplot.rb:73:in `open'
        from sin_wave.rb:3:in `<main>'

**Comment by DouglasAllen** [comment]
Since I see that this version is different I went ahead and installed 2.6.1 this one and tests, and some examples work just fine. But I am now getting an error with the Rake task to install and s few others.
One is with the generated gemspec.
rake aborted!
ArgumentError: $SAFE=2 to 4 are obsolete
gnuplot.gemspec:1:in `block in parse'
Tasks: TOP => install => build
But again the gem at rubygems will suffice for me even though I learned a thing or two with this master.

**Comment by rdp** [comment]
2.6.2 failed but 2.6.1 passed?

On Sat, Nov 12, 2016 at 11:20 PM, Douglas G. Allen <notifications@github.com
